// Generated by jextract

package org.cuelang.libcue;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "cue_dec_bool",
        constants$3.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "cue_dec_double",
        constants$3.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "cue_dec_string",
        constants$3.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "cue_dec_bytes",
        constants$0.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "cue_dec_json",
        constants$0.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "cue_validate",
        constants$3.const$0
    );
}


