// Generated by jextract

package org.cuelang.libcue;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "cue_lookup_string",
        constants$2.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "cue_from_int64",
        constants$3.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "cue_from_uint64",
        constants$3.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "cue_from_bool",
        constants$4.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_LONG,
        JAVA_DOUBLE
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "cue_from_double",
        constants$4.const$5
    );
}


