// Generated by jextract

package org.cuelang.libcue;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "cue_disallow_cycles",
        constants$9.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "cue_docs",
        constants$9.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "cue_errors_as_values",
        constants$9.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "cue_final",
        constants$9.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "cue_hidden",
        constants$9.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "cue_inline_imports",
        constants$9.const$2
    );
}


