#!/bin/sh

set -e
srcdir="$(cd `dirname "$0"` && pwd)"
cd "$srcdir"

# TODO: remove this.
PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

javac --enable-preview --source=21 -sourcepath org/cuelang/libcue org/cuelang/libcue/*.java
javac --enable-preview --source=21 -sourcepath org/cuelang/cue org/cuelang/cue/*.java
