#!/usr/bin/env bash
set -euo pipefail

# Change into the project's root directory.
cd "$(dirname "$0")"

# Allow for a machine-specific pointer to the jextract executable to be
# communicated via the JEXTPATH variable, defaulting to a value for one
# specific developer's machine.
if ! command -v jextract >/dev/null; then
    : ${JEXTPATH:=$HOME/src/jextract-22/bin}
    PATH=$PATH:$JEXTPATH
fi

# Allow for a machine-specific pointer to the source of libcue to be
# communicated via the LIBCUE variable, defaulting to a value for one specific
# developer's machine.
: ${LIBCUE:=$HOME/src/libcue}

find src/main/java/org/cuelang/libcue -type f -not -name 'gen.go' -delete
jextract -t org.cuelang.libcue --output src/main/java -lcue --use-system-load-library @includes.txt "$LIBCUE/cue.h"
