// Generated by jextract

package org.cuelang.libcue;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$9 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$9() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("tag"),
        JAVA_BOOLEAN.withName("value"),
        MemoryLayout.paddingLayout(3)
    ).withName("cue_eopt"));
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "cue_all",
        constants$9.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("tag"),
        JAVA_BOOLEAN.withName("value"),
        MemoryLayout.paddingLayout(3)
    ).withName("cue_eopt"),
        JAVA_BOOLEAN
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "cue_attributes",
        constants$9.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "cue_concrete",
        constants$9.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "cue_definitions",
        constants$9.const$2
    );
}


