// Generated by jextract

package org.cuelang.libcue;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct cue_attr_arg {
 *     char* key;
 *     char* val;
 * };
 * }
 */
public class cue_attr_arg {

    public static MemoryLayout $LAYOUT() {
        return constants$0.const$0;
    }
    public static VarHandle key$VH() {
        return constants$0.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* key;
     * }
     */
    public static MemorySegment key$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$0.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* key;
     * }
     */
    public static void key$set(MemorySegment seg, MemorySegment x) {
        constants$0.const$1.set(seg, x);
    }
    public static MemorySegment key$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$0.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void key$set(MemorySegment seg, long index, MemorySegment x) {
        constants$0.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle val$VH() {
        return constants$0.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* val;
     * }
     */
    public static MemorySegment val$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$0.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* val;
     * }
     */
    public static void val$set(MemorySegment seg, MemorySegment x) {
        constants$0.const$2.set(seg, x);
    }
    public static MemorySegment val$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$0.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void val$set(MemorySegment seg, long index, MemorySegment x) {
        constants$0.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


